# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api/v1

# регистрация пользователя
POST {{baseUrl}}/user/register/
Content-Type: application/json

{
    "surname": "Filippov",
    "name": "Aleksander",
    "patronymic": "Nicolaevich",
    "email": "sash5.f@mail.ru",
    "password": "Daiojkghrth86g",
    "password_rep": "Daiojkghrth86g",
    "company": "techconsur",
    "position": "manager",
    "type": "shop"
}

###

# авторизация пользователей
POST {{baseUrl}}/user/login/
Content-Type: application/json

{
    "email": "sash5.f@mail.ru",
    "password": "Daiojkghrth86g"
}

###

# создание контакта пользователем
POST {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 897cb3ca10acb3965e96cd69792c1a027356c0fb

{
    "type": "buyer",
    "value": "gto",
    "city": "NN",
    "street": "Kerchenskaya",
    "phone": "89102362565"
}

###

# удаление контакта пользователем
DELETE  {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 5d4ad4646630935592b88d104a4e6095c32376a6

###

# просмотр контакта пользователем
GET  {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 5d4ad4646630935592b88d104a4e6095c32376a6

###

# редактирование контакта пользователем
PUT  {{baseUrl}}/user/contact/
Content-Type: application/json
Authorization: Token 897cb3ca10acb3965e96cd69792c1a027356c0fb

{
    "type": "buyer",
    "value": "gto",
    "city": "NN3",
    "street": "Kerchenskaya",
    "phone": "89102362565"
}

###

# подтверждение почтового адреса пользователей
POST {{baseUrl}}/user/register/confirm/
Content-Type: application/json

{
    "email": "sashf.f@mail.ru",
    "token": "5d4ad4646630935592b88d104a4e6095c32376a6"
}

###

# обновление прайса магазином
POST {{baseUrl}}/partner/update/
Content-Type: application/json
Authorization: Token 897cb3ca10acb3965e96cd69792c1a027356c0fb

{
    "url": "https://partner-site.ru/files/price.yaml"

}

###

# создание магазина
POST {{baseUrl}}/shop/
Content-Type: application/json
Authorization: Token abf62632a0533e390c52204674b2d2aec7ff1fab

{
    "name": "eldorado2",
    "url": "https://www.eldorado.ru"
}

###

# просмотр магазина
GET {{baseUrl}}/shop/
Content-Type: application/json
Authorization: Token 897cb3ca10acb3965e96cd69792c1a027356c0fb

###

# обновление статуса магазина
PATCH {{baseUrl}}/shop/2/
Content-Type: application/json
Authorization: Token 5d4ad4646630935592b88d104a4e6095c32376a6

{
    "state": "true"
}

###

# получение статуса магазина (декоратор @action)
GET {{baseUrl}}/shop/2/state/
Content-Type: application/json
Authorization: Token 5d4ad4646630935592b88d104a4e6095c32376a6

###

# создание категории
POST {{baseUrl}}/category/
Content-Type: application/json
Authorization: Token 927efadd48c5277550ebf198233fba9b7a2b9834

{
    "name": "electronocs"
}

###

# создание продукта (декоратор @action)
POST {{baseUrl}}/products/write/
Content-Type: application/json
Authorization: Token abf62632a0533e390c52204674b2d2aec7ff1fab

{
    "model": "Samsung25545",
    "name": "Phone",
    "shop": 1,
    "category": 1,
    "quantity": 2,
    "price": 50,
    "price_rrc": 55   
}

###

# получение списка продуктов
GET {{baseUrl}}/products/
Content-Type: application/json
Authorization: Token abf62632a0533e390c52204674b2d2aec7ff1fab

###


# поиск товаров в каталоге
GET {{baseUrl}}/products/?category=224&shop=2
Content-Type: application/json
Authorization: Token abf62632a0533e390c52204674b2d2aec7ff1fab

###

# добавление заказа в корзину покупателем
POST {{baseUrl}}/basket/
Content-Type: application/json
Authorization: Token 0d76c67d9530e179210835cb4095dc90a78d4836

{
    "product_id": 1,
    "shop_id": 1,
    "quantity": 0
}

###

# удаление заказа из корзины покупателем
DELETE {{baseUrl}}/basket/2/
Content-Type: application/json
Authorization: Token 840b17b99bc625d029a5ce157d54c4db9c943849

###

# размещение заказа покупателем
POST {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 0d76c67d9530e179210835cb4095dc90a78d4836

###

# просмотр заказа покупателем/продавцом
GET {{baseUrl}}/order/4/
Content-Type: application/json
Authorization: Token 0d76c67d9530e179210835cb4095dc90a78d4836

###

# просмотр списка заказов покупателем/продавцом
GET {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 0d76c67d9530e179210835cb4095dc90a78d4836

###


# обновление статуса заказа магазином
PATCH {{baseUrl}}/order/4/
Content-Type: application/json
Authorization: Token b893b9988e9c248c024d9a5ce42acbef12efa70f

{
    "status": "sent"
}

###












